apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
  params:
    - name: repo-url
      type: string
    - name: image-reference
      type: string
  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: pipeline-workspace
    - name: clone
      taskRef:
        name: git-clone
      runAfter:
        - cleanup
      params:
        - name: url
          value: $(params.repo-url)
      workspaces:
        - name: output
          workspace: pipeline-workspace
    - name: lint
      taskRef:
        name: flake8
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: pipeline-workspace
    - name: test
      taskRef:
        name: nose
      runAfter:
        - lint
      workspaces:
        - name: source
          workspace: pipeline-workspace
    - name: build
      taskRef:
        name: buildah
      runAfter:
        - test
      params:
        - name: IMAGE
          value: $(params.image-reference)
      workspaces:
        - name: source
          workspace: pipeline-workspace
    - name: deploy
      taskRef:
        name: openshift-client
      runAfter:
        - build
      params:
        - name: SCRIPT
          value: |
            oc new-app $(params.image-reference) --name=sample-app
